(() => {
"use strict";
let scene, camera, renderer, clock;
let player = null;
let caveMode = false;
let rotatingCamera = false;
let selectedClass = "demon";
let uiOpen = false;
const keys = {};
const settings = { mobileControls: false };
const mouse = { yaw: Math.PI, pitch: 0.35, distance: 9.5 };
const hotbar = { active: 1 };
const state = {money:0,level:1,xp:0,xpNext:20,health:100,maxHealth:100,iron:0,crystal:0,hasPickaxe:false,hasIronPickaxe:false,weapon:"Base Weapon",weaponDamage:8};
let questNpc, caveDoor, oreNode, crystalNode; let caveObjects=[];
const $=(id)=>document.getElementById(id);
window.startGame=function(type){try{selectedClass=type;state.weapon=baseWeaponName();$("slot1").textContent=state.weapon;$("weapon").textContent="Weapon: "+state.weapon;$("start-screen").classList.add("hidden");$("hud").classList.remove("hidden");$("hotbar").classList.remove("hidden");init();animate();}catch(err){showError(err);}};
window.toggleInventory=function(force){const el=$("inventory");const open=typeof force==="boolean"?force:el.classList.contains("hidden");if(open){el.classList.remove("hidden");uiOpen=true;renderInventory();}else{el.classList.add("hidden");uiOpen=false;}};
window.toggleSettings=function(force){const el=$("settings");const open=typeof force==="boolean"?force:el.classList.contains("hidden");if(open){el.classList.remove("hidden");uiOpen=true;}else{el.classList.add("hidden");uiOpen=false;}};
function baseWeaponName(){return selectedClass==="beast"?"Claws":selectedClass==="mage"?"Staff":"Blood Magic";}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x87a8cc);scene.fog=new THREE.Fog(0x87a8cc,70,220);camera=new THREE.PerspectiveCamera(70,window.innerWidth/window.innerHeight,0.1,500);camera.position.set(0,7,16);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:"high-performance"});renderer.setSize(window.innerWidth,window.innerHeight);renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));document.body.appendChild(renderer.domElement);clock=new THREE.Clock();const hemi=new THREE.HemisphereLight(0xffffff,0x334155,1.2);const sun=new THREE.DirectionalLight(0xffffff,1.0);sun.position.set(30,40,20);scene.add(hemi,sun);buildTown();player=createPlayer();player.mesh.position.set(0,0,8);bindEvents();updateHud();updateArea("Town");showMessage("Welcome to town.");showAlert("Discovered: Town");}
function bindEvents(){window.addEventListener("resize",onResize);document.addEventListener("keydown",onKeyDown);document.addEventListener("keyup",onKeyUp);renderer.domElement.addEventListener("mousedown",onMouseDown);renderer.domElement.addEventListener("mouseup",onMouseUp);renderer.domElement.addEventListener("mousemove",onMouseMove);$("settings-btn").addEventListener("click",()=>window.toggleSettings(true));$("fullscreen-btn").addEventListener("click",toggleFullscreen);$("mobile-toggle").addEventListener("change",e=>setMobileControls(e.target.checked));document.querySelectorAll("#move-pad button").forEach(btn=>{btn.addEventListener("touchstart",e=>{e.preventDefault();keys[btn.dataset.key]=true;},{passive:false});btn.addEventListener("touchend",e=>{e.preventDefault();keys[btn.dataset.key]=false;},{passive:false});});document.querySelectorAll("#action-pad button").forEach(btn=>{btn.addEventListener("touchstart",e=>{e.preventDefault();const a=btn.dataset.action;if(a==="attack")beginAttack();if(a==="interact")tryInteract();if(a==="inventory")window.toggleInventory();if(a==="cam-left")mouse.yaw+=0.2;if(a==="cam-right")mouse.yaw-=0.2;},{passive:false});});}
function onResize(){if(!camera||!renderer)return;camera.aspect=window.innerWidth/window.innerHeight;camera.updateProjectionMatrix();renderer.setSize(window.innerWidth,window.innerHeight);}
function onKeyDown(e){const key=e.key.toLowerCase();keys[key]=true;if(key==="e")tryInteract();if(key==="i")window.toggleInventory();if(["1","2","3"].includes(key)){hotbar.active=Number(key);updateHotbar();applyHotbar();}}
function onKeyUp(e){keys[e.key.toLowerCase()]=false;}
function onMouseDown(e){if(uiOpen)return;if(e.button===2)rotatingCamera=true;if(e.button===0)beginAttack();}
function onMouseUp(e){if(e.button===2)rotatingCamera=false;}
function onMouseMove(e){if(!rotatingCamera||uiOpen)return;mouse.yaw-=e.movementX*0.006;mouse.pitch+=e.movementY*0.003;mouse.pitch=clamp(mouse.pitch,0.15,0.9);}
function toggleFullscreen(){if(!document.fullscreenElement)document.documentElement.requestFullscreen().catch(()=>{});else document.exitFullscreen().catch(()=>{});}
function setMobileControls(enabled){settings.mobileControls=enabled;$("mobile-controls").classList.toggle("hidden",!enabled);}
function buildTown(){const ground=new THREE.Mesh(new THREE.PlaneGeometry(420,420),new THREE.MeshStandardMaterial({color:0x6d8754}));ground.rotation.x=-Math.PI/2;scene.add(ground);const plaza=new THREE.Mesh(new THREE.CircleGeometry(28,56),new THREE.MeshStandardMaterial({color:0xa5aab2}));plaza.rotation.x=-Math.PI/2;plaza.position.y=0.03;scene.add(plaza);addBuilding(-24,-18,0x8b5e3c,"Forge");addBuilding(24,-18,0x7b5537,"Supplies");addBuilding(0,24,0x59616f,"Town Hall");questNpc=createNpc(-10,-2,0x3b82f6);oreNode=createOreNode(34,8);caveDoor=new THREE.Mesh(new THREE.CylinderGeometry(4,5.5,5,20),new THREE.MeshStandardMaterial({color:0x4b5563}));caveDoor.position.set(88,2.5,18);scene.add(caveDoor);addSign("Crystal Cave",88,6.5,14.5);for(let i=0;i<90;i++){const a=(Math.PI*2*i)/90;const r=72+Math.random()*48;const x=Math.cos(a)*r;const z=Math.sin(a)*r;if(Math.abs(x)<60&&Math.abs(z)<60)continue;createTree(x,z);}}
function addBuilding(x,z,color,label){const body=new THREE.Mesh(new THREE.BoxGeometry(15,7,11),new THREE.MeshStandardMaterial({color}));body.position.set(x,3.5,z);scene.add(body);const roof=new THREE.Mesh(new THREE.ConeGeometry(10.5,3.6,4),new THREE.MeshStandardMaterial({color:0x3b2f2f}));roof.position.set(x,8.2,z);roof.rotation.y=Math.PI*0.25;scene.add(roof);addSign(label,x,5.8,z-6.1);}
function addSign(text,x,y,z){const make=()=>{const canvas=document.createElement("canvas");canvas.width=320;canvas.height=96;const ctx=canvas.getContext("2d");ctx.fillStyle="#f2d39b";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#6b4423";ctx.lineWidth=8;ctx.strokeRect(4,4,canvas.width-8,canvas.height-8);ctx.fillStyle="#2f2418";ctx.font="bold 30px Arial";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(text,canvas.width/2,canvas.height/2);return new THREE.Mesh(new THREE.PlaneGeometry(6.1,1.95),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(canvas),transparent:true}));};const front=make();front.position.set(x,y,z);scene.add(front);const back=make();back.position.set(x,y,z+0.03);back.rotation.y=Math.PI;scene.add(back);}
function createNpc(x,z,color){const g=new THREE.Group();const torso=new THREE.Mesh(new THREE.BoxGeometry(0.9,1.2,0.55),new THREE.MeshStandardMaterial({color}));torso.position.y=1.2;g.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(0.35,14,14),new THREE.MeshStandardMaterial({color:0xf1c27d}));head.position.y=2.15;g.add(head);const leftLeg=new THREE.Mesh(new THREE.BoxGeometry(0.28,1,0.28),new THREE.MeshStandardMaterial({color:0x1f2937}));leftLeg.position.set(-0.22,0.45,0);g.add(leftLeg);const rightLeg=leftLeg.clone();rightLeg.position.x=0.22;g.add(rightLeg);g.position.set(x,0,z);scene.add(g);return g;}
function createTree(x,z){const trunk=new THREE.Mesh(new THREE.CylinderGeometry(0.35,0.45,3.2,8),new THREE.MeshStandardMaterial({color:0x6b4423}));trunk.position.set(x,1.6,z);scene.add(trunk);const leaves=new THREE.Mesh(new THREE.SphereGeometry(1.7,12,12),new THREE.MeshStandardMaterial({color:0x2f6b32}));leaves.position.set(x,4.3,z);scene.add(leaves);}
function createOreNode(x,z){const ore=new THREE.Mesh(new THREE.DodecahedronGeometry(0.9,0),new THREE.MeshStandardMaterial({color:0x6b7280}));ore.position.set(x,1,z);scene.add(ore);return ore;}
function createCrystalNode(x,z){const crystal=new THREE.Mesh(new THREE.OctahedronGeometry(1.1,0),new THREE.MeshStandardMaterial({color:0x7c3aed,emissive:0x4c1d95,emissiveIntensity:0.35}));crystal.position.set(x,1.3,z);scene.add(crystal);return crystal;}
function createPlayer(){const colors={demon:0x7f1d1d,mage:0x4338ca,beast:0x7c2d12};const g=new THREE.Group();const torso=new THREE.Mesh(new THREE.BoxGeometry(1,1.35,0.65),new THREE.MeshStandardMaterial({color:colors[selectedClass]}));torso.position.y=1.25;g.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(0.38,16,16),new THREE.MeshStandardMaterial({color:0xf1c27d}));head.position.y=2.25;g.add(head);const leftArm=new THREE.Mesh(new THREE.BoxGeometry(0.24,1.05,0.24),new THREE.MeshStandardMaterial({color:colors[selectedClass]}));leftArm.position.set(-0.72,1.25,0);g.add(leftArm);const rightArm=leftArm.clone();rightArm.position.x=0.72;g.add(rightArm);const leftLeg=new THREE.Mesh(new THREE.BoxGeometry(0.3,1.1,0.3),new THREE.MeshStandardMaterial({color:0x111827}));leftLeg.position.set(-0.24,0.5,0);g.add(leftLeg);const rightLeg=leftLeg.clone();rightLeg.position.x=0.24;g.add(rightLeg);if(selectedClass==="mage"){const hat=new THREE.Mesh(new THREE.ConeGeometry(0.55,1.25,12),new THREE.MeshStandardMaterial({color:0x111827}));hat.position.y=2.95;g.add(hat);}if(selectedClass==="demon"){const horn1=new THREE.Mesh(new THREE.ConeGeometry(0.14,0.55,10),new THREE.MeshStandardMaterial({color:0x111827}));horn1.position.set(0.2,2.75,0.05);horn1.rotation.z=-0.5;g.add(horn1);const horn2=horn1.clone();horn2.position.x=-0.2;horn2.rotation.z=0.5;g.add(horn2);}if(selectedClass==="beast"){const ear1=new THREE.Mesh(new THREE.ConeGeometry(0.12,0.45,10),new THREE.MeshStandardMaterial({color:0x3f2a18}));ear1.position.set(0.23,2.75,0);g.add(ear1);const ear2=ear1.clone();ear2.position.x=-0.23;g.add(ear2);}const weaponMesh=createBaseWeapon();weaponMesh.position.set(0.92,1.18,0);g.add(weaponMesh);const pickaxeMesh=createPickaxe();pickaxeMesh.position.set(0.92,1.18,0);pickaxeMesh.visible=false;g.add(pickaxeMesh);scene.add(g);return {mesh:g,weaponMesh,pickaxeMesh,velocity:new THREE.Vector3(),moveSpeed:5.8,sprintSpeed:9.0,attacking:false,attackTimer:0,attackCooldown:0};}
function createBaseWeapon(){if(selectedClass==="beast"){const g=new THREE.Group();for(let i=0;i<3;i++){const claw=new THREE.Mesh(new THREE.ConeGeometry(0.05,0.7,8),new THREE.MeshStandardMaterial({color:0xdbe3ec}));claw.rotation.x=Math.PI/2;claw.position.set(0.08*i-0.08,0,0.2+i*0.05);g.add(claw);}g.rotation.z=0.2;return g;}if(selectedClass==="mage"){const g=new THREE.Group();const staff=new THREE.Mesh(new THREE.CylinderGeometry(0.05,0.05,1.8,8),new THREE.MeshStandardMaterial({color:0x7c5a34}));staff.rotation.z=0.2;g.add(staff);const orb=new THREE.Mesh(new THREE.SphereGeometry(0.16,12,12),new THREE.MeshStandardMaterial({color:0x60a5fa,emissive:0x2563eb,emissiveIntensity:0.6}));orb.position.set(0.18,0.82,0);g.add(orb);return g;}const g=new THREE.Group();const core=new THREE.Mesh(new THREE.SphereGeometry(0.18,12,12),new THREE.MeshStandardMaterial({color:0x7f1d1d,emissive:0x7f1d1d,emissiveIntensity:0.8}));g.add(core);const aura=new THREE.Mesh(new THREE.SphereGeometry(0.28,12,12),new THREE.MeshBasicMaterial({color:0xdc2626,transparent:true,opacity:0.35}));g.add(aura);return g;}
function createPickaxe(){const g=new THREE.Group();const handle=new THREE.Mesh(new THREE.CylinderGeometry(0.05,0.05,1.55,10),new THREE.MeshStandardMaterial({color:0x7c5a34}));handle.rotation.z=0.4;g.add(handle);const head=new THREE.Mesh(new THREE.BoxGeometry(0.85,0.14,0.16),new THREE.MeshStandardMaterial({color:0x9ca3af}));head.position.set(0.26,0.56,0);head.rotation.z=0.4;g.add(head);return g;}
function beginAttack(){if(hotbar.active===2&&(state.hasPickaxe||state.hasIronPickaxe)){showMessage("Pickaxe equipped.");return;}if(player.attackCooldown>0)return;player.attacking=true;player.attackTimer=0;player.attackCooldown=0.42;}
function tryInteract(){if(!player)return;const p=player.mesh.position;if(!caveMode&&p.distanceTo(caveDoor.position)<8){enterCave();return;}if(caveMode&&p.distanceTo(new THREE.Vector3(0,0,145))<8){exitCave(false);return;}if(p.distanceTo(questNpc.position)<4){if(!state.hasPickaxe){state.hasPickaxe=true;$("slot2").textContent="Pickaxe";$("quest").textContent="Mine 1 iron, then return.";showMessage("You got a basic pickaxe.");renderInventory();}else{showMessage("Keep going.");}return;}if(!caveMode&&oreNode&&oreNode.visible&&p.distanceTo(oreNode.position)<3){if(!state.hasPickaxe&&!state.hasIronPickaxe){showMessage("You need a pickaxe first.");return;}if(hotbar.active!==2){showMessage("Equip the pickaxe in slot 2.");return;}state.iron+=1;oreNode.visible=false;showMessage("You mined iron.");if(!state.hasIronPickaxe&&state.iron>=1){state.hasIronPickaxe=true;$("slot2").textContent="Iron Pickaxe";showMessage("Your pickaxe upgraded.");}updateHud();renderInventory();return;}if(caveMode&&crystalNode&&crystalNode.visible&&p.distanceTo(crystalNode.position)<3){if(!state.hasIronPickaxe){showMessage("You need an Iron Pickaxe to mine crystal.");return;}if(hotbar.active!==2){showMessage("Equip the pickaxe in slot 2.");return;}state.crystal+=1;crystalNode.visible=false;showMessage("You mined crystal.");updateHud();renderInventory();return;}showMessage("Nothing to interact with.");}
function enterCave(){caveMode=true;scene.background=new THREE.Color(0x050507);scene.fog=new THREE.Fog(0x000000,5,70);const floor=new THREE.Mesh(new THREE.CircleGeometry(34,60),new THREE.MeshStandardMaterial({color:0x353535}));floor.rotation.x=-Math.PI/2;floor.position.set(0,-0.02,160);scene.add(floor);caveObjects.push(floor);const ceiling=new THREE.Mesh(new THREE.CircleGeometry(34,60),new THREE.MeshStandardMaterial({color:0x151515,side:THREE.DoubleSide}));ceiling.rotation.x=Math.PI/2;ceiling.position.set(0,18,160);scene.add(ceiling);caveObjects.push(ceiling);for(let i=0;i<10;i++){const wall=new THREE.Mesh(new THREE.BoxGeometry(10,12,4),new THREE.MeshStandardMaterial({color:0x4a4036}));const a=(Math.PI*2*i)/10;wall.position.set(Math.cos(a)*30,6,160+Math.sin(a)*30);wall.lookAt(0,6,160);scene.add(wall);caveObjects.push(wall);}for(let i=0;i<8;i++){const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(1.2+Math.random()*1.2,0),new THREE.MeshStandardMaterial({color:0x5b5148}));rock.position.set(-20+Math.random()*40,1+Math.random()*2,145+Math.random()*24);scene.add(rock);caveObjects.push(rock);}for(let i=0;i<4;i++){const torch=new THREE.PointLight(0xffb74d,1.2,25);torch.position.set(-18+i*12,6,150+(i%2)*8);scene.add(torch);caveObjects.push(torch);}crystalNode=createCrystalNode(4,166);caveObjects.push(crystalNode);player.mesh.position.set(0,0,145);updateArea("Crystal Cavern");showMessage("You entered the Crystal Cavern.");showAlert("Discovered: Crystal Cavern");}
function exitCave(toTownSpawn){caveMode=false;for(const obj of caveObjects)scene.remove(obj);caveObjects=[];crystalNode=null;scene.background=new THREE.Color(0x87a8cc);scene.fog=new THREE.Fog(0x87a8cc,70,220);if(toTownSpawn)player.mesh.position.set(0,0,8);else player.mesh.position.set(84,0,24);updateArea("Town");showMessage("You returned to town.");}
function updatePlayer(dt){if(!player||uiOpen)return;const input=new THREE.Vector3();if(keys["w"])input.z-=1;if(keys["s"])input.z+=1;if(keys["a"])input.x-=1;if(keys["d"])input.x+=1;let desired=new THREE.Vector3();if(input.lengthSq()>0){input.normalize();const forward=new THREE.Vector3(Math.sin(mouse.yaw),0,Math.cos(mouse.yaw));const right=new THREE.Vector3(forward.z,0,-forward.x);desired.addScaledVector(forward,-input.z);desired.addScaledVector(right,input.x);desired.normalize();desired.multiplyScalar(keys["shift"]?player.sprintSpeed:player.moveSpeed);player.mesh.rotation.y=Math.atan2(desired.x,desired.z);}player.velocity.lerp(desired,0.18);player.mesh.position.addScaledVector(player.velocity,dt);if(player.attackCooldown>0)player.attackCooldown-=dt;if(player.attacking){player.attackTimer+=dt;const progress=player.attackTimer/0.32;player.weaponMesh.rotation.z=-1.25+Math.min(progress,1)*2.5;if(progress>=1){player.attacking=false;player.weaponMesh.rotation.z=0.18;}}player.mesh.position.x=clamp(player.mesh.position.x,-220,220);player.mesh.position.z=clamp(player.mesh.position.z,-220,220);updateCamera();}
function updateCamera(){const target=new THREE.Vector3(player.mesh.position.x,player.mesh.position.y+1.8,player.mesh.position.z);const shoulder=new THREE.Vector3(1.4,0,0).applyAxisAngle(new THREE.Vector3(0,1,0),mouse.yaw);const offset=new THREE.Vector3(Math.sin(mouse.yaw)*Math.cos(mouse.pitch)*mouse.distance,Math.sin(mouse.pitch)*mouse.distance+1.3,Math.cos(mouse.yaw)*Math.cos(mouse.pitch)*mouse.distance);const desired=target.clone().add(offset).add(shoulder);camera.position.lerp(desired,0.14);camera.lookAt(target.clone().add(new THREE.Vector3(0.8*Math.sin(mouse.yaw),0,0.8*Math.cos(mouse.yaw))));}
function applyHotbar(){if(hotbar.active===2&&(state.hasPickaxe||state.hasIronPickaxe)){player.pickaxeMesh.visible=true;player.weaponMesh.visible=false;state.weapon=state.hasIronPickaxe?"Iron Pickaxe":"Pickaxe";}else{player.pickaxeMesh.visible=false;player.weaponMesh.visible=true;state.weapon=baseWeaponName();}updateHud();}
function updateHotbar(){document.querySelectorAll(".slot").forEach((el,i)=>el.classList.toggle("active",i+1===hotbar.active));}
function updateHud(){$("money").textContent="$"+state.money;$("weapon").textContent="Weapon: "+state.weapon;$("materials").textContent="Iron: "+state.iron+" · Crystal: "+state.crystal;$("hp-fill").style.width=((state.health/state.maxHealth)*100)+"%";$("xp-fill").style.width=((state.xp/state.xpNext)*100)+"%";$("level").textContent=`Level ${state.level} · XP ${state.xp} / ${state.xpNext}`;}
function updateArea(area){$("area").textContent="Area: "+area;}
function renderInventory(){const el=$("inventory-list");el.innerHTML="";["Weapon: "+state.weapon,"Pickaxe: "+(state.hasIronPickaxe?"Iron Pickaxe":state.hasPickaxe?"Basic Pickaxe":"None"),"Iron: "+state.iron,"Crystal: "+state.crystal].forEach(line=>{const div=document.createElement("div");div.textContent=line;el.appendChild(div);});}
function showMessage(text){$("message").textContent=text;}
function showAlert(text){const el=$("alert");el.textContent=text;el.classList.remove("hidden");setTimeout(()=>el.classList.add("hidden"),1800);}
function showError(err){const box=$("error-box");box.textContent="Startup error:\n"+(err&&err.stack?err.stack:String(err));box.classList.remove("hidden");console.error(err);}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),0.05);updatePlayer(dt);updateHud();renderer.render(scene,camera);}function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
window.addEventListener("contextmenu",e=>e.preventDefault());window.addEventListener("error",e=>showError(e.error||e.message||"Unknown runtime error"));
})();